project:
  type: website
  output-dir: .

website:
  title: "Amusons-nous avec Rstudio !"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: lux
    css: styles.css

editor: visual

